services:
  webapi:
    build:
      context: ./caps
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - client

  client:
    build:
      context: ../caps-client
      dockerfile: Dockerfile
    command: sh -c "npm start"
    volumes:
      - ../caps-client:/home/node/app
      - /home/node/app/node_modules #
    ports:
      - "4200:4200"
    working_dir: /home/node/app
volumes:
  node_modules:
