services:
  webapi:
    build:
      context: .
      dockerfile: ./caps/Dockerfile.Prod
      platforms:
        - linux/amd64
    ports:
      - "80:8080"
    environment:
      - MONGO_DATABASE_URL=mongodb://mongodb:27017
      - MONGO_DATABASE_NAME=sample_planets
      - JWT_SECRET_KEY=THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET
      - JWT_EXPIRE_MINS=120
      - ADMIN_DEFAULT_PASSWORD=12qw!@QW
      - API_URL=http://185.144.158.162
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
