services:
  webapi:
    build:
      context: .
      dockerfile: ./caps/Dockerfile.Dev
    ports:
      - "8080:8080"
    depends_on:
      - client
    environment:
      - MONGO_DATABASE_URL=mongodb://mongodb:27017
      - MONGO_DATABASE_NAME=sample_planets
      - JWT_SECRET_KEY=THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET_THIS_IS_A_LONG_SECRET
      - JWT_EXPIRE_MINS=120
      - ADMIN_DEFAULT_PASSWORD_HASH=71F62B0012EB17B1D686B19CE0C58F2B476DF144117DE48BEFADA3BE76E3AD11-83C24BEE9C1AF4A3545B5CC0389ECBBE
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  client:
    build:
      context: .
      dockerfile: ./caps-client/Dockerfile
    command: sh -c "npm start"
    volumes:
      - ./caps-client:/home/node/app
      - /home/node/app/node_modules #
    environment:
      - BACKEND_URL=http://webapi:80
    ports:
      - "4200:4200"
    working_dir: /home/node/app
volumes:
  node_modules:
