export enum AgentRole {
  Admin = 'Admin',
  Professional = 'Professional',
  Intern = 'Intern',
}

export const AGENT_PRIVILEGES = [AgentRole.Professional, AgentRole.Intern];

export const StrongPasswordRegx: RegExp =
  // /^(?=[^A-Z]*[A-Z])(?=[^a-z]*[a-z])(?=\D*\d).{8,}$/;
  /^(?=[^A-Z]*[A-Z])(?=[^a-z]*[a-z])(?=\D*\d)(?=.*[!@#$%^&*]).{8,}$/;

export const HONDURAS_DEPARTMENTS = [
  'Atlántida',
  'Colón',
  'Comayagua',
  'Copán',
  'Cortés',
  'Choluteca',
  'El Paraíso',
  'Francisco Morazán',
  'Gracias a Dios',
  'Intibucá',
  'Islas de la Bahía',
  'La Paz',
  'Lempira',
  'Ocotepeque',
  'Olancho',
  'Santa Bárbara',
  'Valle',
  'Yoro',
];

export const DIAGNOSTIC_OPTIONS = [
  // "Otro en Diagnostico #2",
  'Trastorno del Espectro Autista',
  'Trastorno por Déficit de Atención e Hiperactividad (TDAH)',
  'Discapacidad Intelectual',
  'Trastornos Específicos del Aprendizaje',
  'Trastornos de la Comunicación',
  'Trastorno del Desarrollo de la Coordinación',
  'Trastornos Motores (incluyendo el Trastorno de Tics)',
  'Esquizofrenia',
  'Trastorno Esquizoafectivo',
  'Trastorno Psicótico Breve',
  'Trastorno Esquizofreniforme',
  'Trastorno Delirante',
  'Trastorno Bipolar I',
  'Trastorno Bipolar II',
  'Trastorno Ciclotímico',
  'Trastorno Depresivo Mayor',
  'Trastorno Distímico (Trastorno Depresivo Persistente)',
  'Trastorno Disfórico Premenstrual',
  'Trastorno Depresivo Inducido por Sustancias/Medicamentos',
  'Trastorno de Ansiedad Generalizada',
  'Trastorno de Pánico',
  'Fobia Específica',
  'Trastorno de Ansiedad Social (Fobia Social)',
  'Agorafobia',
  'Trastorno Obsesivo-Compulsivo (TOC)',
  'Trastorno Dismórfico Corporal',
  'Trastorno de Acumulación',
  'Tricotilomanía (Arrancamiento del Cabello)',
  'Trastorno de Excoriación (Rascado Compulsivo)',
  'Trastorno de Estrés Postraumático (TEPT)',
  'Trastorno de Estrés Agudo',
  'Trastorno de Adaptación',
  'Trastorno Reactivo del Apego',
  'Trastorno de Identidad Disociativo',
  'Amnesia Disociativa',
  'Despersonalización/Desrealización',
  'Trastorno de Síntomas Somáticos',
  'Trastorno de Ansiedad por Enfermedad',
  'Trastorno de Conversión (Trastorno de Síntomas Neurológicos Funcionales)',
  'Factitious Disorder (Trastorno Facticio)',
  'Anorexia Nerviosa',
  'Bulimia Nerviosa',
  'Trastorno de Atracones',
  'Enuresis',
  'Encopresis',
  'Insomnio',
  'Narcolepsia',
  'Trastornos del Sueño Relacionados con la Respiración',
  'Trastornos del Ritmo Circadiano del Sueño',
  'Disfunción Eréctil',
  'Trastorno de Deseo Sexual Hipoactivo',
  'Trastorno Orgásmico Femenino',
  'Trastorno del Dolor Genito-Pélvico/Penetración',
  'Disforia de Género en Niños',
  'Disforia de Género en Adolescentes y Adultos',
  'Trastorno Negativista Desafiante',
  'Trastorno Explosivo Intermitente',
  'Trastorno de la Conducta',
  'Trastorno Antisocial de la Personalidad',
  'Piromanía',
  'Cleptomanía',
  'Trastorno por Uso de Alcohol',
  'Trastorno por Uso de Sustancias (por ejemplo, opioides, cannabis, cocaína)',
  'Juego Patológico',
  'Delirium',
  'Trastorno Neurocognitivo Mayor (Demencia)',
  'Trastorno Neurocognitivo Leve',
  'Trastorno de Personalidad Paranoide',
  'Trastorno de Personalidad Esquizoide',
  'Trastorno de Personalidad Esquizotípico',
  'Trastorno de Personalidad Antisocial',
  'Trastorno de Personalidad Límite (Borderline)',
  'Trastorno de Personalidad Histriónica',
  'Trastorno de Personalidad Narcisista',
  'Trastorno de Personalidad Evitativa',
  'Trastorno de Personalidad Dependiente',
  'Trastorno de Personalidad Obsesivo-Compulsivo',
  'Voyeurismo',
  'Exhibicionismo',
  'Frotteurismo',
  'Masoquismo Sexual',
  'Sadismo Sexual',
  'Pedofilia',
  'Fetichismo',
  'Transvestismo',
  'Trastorno de Duelo Prolongado',
  'Trastorno de Síntomas Psicológicos y Conductuales Asociados con Otras Condiciones Médicas',
];

export const TASK_OPTIONS = [
  'Monitored alimenticio',
  'Monitored sueno',
  'Monitored emocional',
  'Amplied for antennal resection',
  'Other Task',
];

export const INTERVENTION_OPTIONS = [
  'N/A',
  'Primeros auxilios psicológicos',
  'Terapia de crisis',
  'Consejería',
  'Terapia breve',
  'Evaluacion Vocacional',
  'Orientacion vocacional',
  'Neurofeedback',
  'Programa de funciones ejecutivas',
  'Other Intervention',
];

export const PROGRAMS = [
  'Otro',
  'Glasswing',
  'Club Rotario',
  'World Vision',
  'UNAH-VS',
  'Red Inter Salud Mental',
];

export const APPOINTMENT_STATUSES = {
  SCHEDULED: 'Scheduled',
  CANCELED: 'Canceled',
  COMPLETED: 'Completed',
};
